import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "hizmetler" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "hizmetler" DROP COLUMN "onaylayan";
  ALTER TABLE "hizmetler" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "hizmetler" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_hizmetler_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_hizmetler_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_hizmetler_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_hizmetler_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "kullanim_alanlari" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "kullanim_alanlari" DROP COLUMN "onaylayan";
  ALTER TABLE "kullanim_alanlari" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "kullanim_alanlari" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_kullanim_alanlari_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_kullanim_alanlari_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_kullanim_alanlari_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_kullanim_alanlari_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "islem_secenekleri" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "islem_secenekleri" DROP COLUMN "onaylayan";
  ALTER TABLE "islem_secenekleri" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "islem_secenekleri" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_islem_secenekleri_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_islem_secenekleri_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_islem_secenekleri_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_islem_secenekleri_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "uygulamalar" DROP COLUMN "yayin_izni";
  ALTER TABLE "uygulamalar" DROP COLUMN "izin_notu";
  ALTER TABLE "uygulamalar" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "uygulamalar" DROP COLUMN "onaylayan";
  ALTER TABLE "uygulamalar" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "uygulamalar" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_uygulamalar_v" DROP COLUMN "version_yayin_izni";
  ALTER TABLE "_uygulamalar_v" DROP COLUMN "version_izin_notu";
  ALTER TABLE "_uygulamalar_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_uygulamalar_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_uygulamalar_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_uygulamalar_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "sss" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "sss" DROP COLUMN "onaylayan";
  ALTER TABLE "sss" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "sss" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_sss_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_sss_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_sss_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_sss_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "rehber_yazilari" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "rehber_yazilari" DROP COLUMN "onaylayan";
  ALTER TABLE "rehber_yazilari" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "rehber_yazilari" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_rehber_yazilari_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_rehber_yazilari_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_rehber_yazilari_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_rehber_yazilari_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "sayfalar" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "sayfalar" DROP COLUMN "onaylayan";
  ALTER TABLE "sayfalar" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "sayfalar" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_sayfalar_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_sayfalar_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_sayfalar_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_sayfalar_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "kampanyalar" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "kampanyalar" DROP COLUMN "onaylayan";
  ALTER TABLE "kampanyalar" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "kampanyalar" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_kampanyalar_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_kampanyalar_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_kampanyalar_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_kampanyalar_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "yorumlar" DROP COLUMN "yayin_izni";
  ALTER TABLE "yorumlar" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "yorumlar" DROP COLUMN "onaylayan";
  ALTER TABLE "yorumlar" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "yorumlar" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "_yorumlar_v" DROP COLUMN "version_yayin_izni";
  ALTER TABLE "_yorumlar_v" DROP COLUMN "version_dogrulama_durumu";
  ALTER TABLE "_yorumlar_v" DROP COLUMN "version_onaylayan";
  ALTER TABLE "_yorumlar_v" DROP COLUMN "version_dogrulama_tarihi";
  ALTER TABLE "_yorumlar_v" DROP COLUMN "version_dahili_kaynak_notu";
  ALTER TABLE "medyalar" DROP COLUMN "yayin_izni";
  ALTER TABLE "medyalar" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "medyalar" DROP COLUMN "onaylayan";
  ALTER TABLE "medyalar" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "medyalar" DROP COLUMN "dahili_kaynak_notu";
  ALTER TABLE "dosyalar" DROP COLUMN "dogrulama_durumu";
  ALTER TABLE "dosyalar" DROP COLUMN "onaylayan";
  ALTER TABLE "dosyalar" DROP COLUMN "dogrulama_tarihi";
  ALTER TABLE "dosyalar" DROP COLUMN "dahili_kaynak_notu";
  DROP TYPE "public"."enum_hizmetler_dogrulama_durumu";
  DROP TYPE "public"."enum__hizmetler_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_kullanim_alanlari_dogrulama_durumu";
  DROP TYPE "public"."enum__kullanim_alanlari_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_islem_secenekleri_dogrulama_durumu";
  DROP TYPE "public"."enum__islem_secenekleri_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_uygulamalar_dogrulama_durumu";
  DROP TYPE "public"."enum__uygulamalar_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_sss_dogrulama_durumu";
  DROP TYPE "public"."enum__sss_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_rehber_yazilari_dogrulama_durumu";
  DROP TYPE "public"."enum__rehber_yazilari_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_sayfalar_dogrulama_durumu";
  DROP TYPE "public"."enum__sayfalar_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_kampanyalar_dogrulama_durumu";
  DROP TYPE "public"."enum__kampanyalar_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_yorumlar_dogrulama_durumu";
  DROP TYPE "public"."enum__yorumlar_v_version_dogrulama_durumu";
  DROP TYPE "public"."enum_medyalar_dogrulama_durumu";
  DROP TYPE "public"."enum_dosyalar_dogrulama_durumu";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_hizmetler_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__hizmetler_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_kullanim_alanlari_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__kullanim_alanlari_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_islem_secenekleri_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__islem_secenekleri_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_uygulamalar_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__uygulamalar_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_sss_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__sss_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_rehber_yazilari_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__rehber_yazilari_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_sayfalar_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__sayfalar_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_kampanyalar_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__kampanyalar_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_yorumlar_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum__yorumlar_v_version_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_medyalar_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  CREATE TYPE "public"."enum_dosyalar_dogrulama_durumu" AS ENUM('bekliyor', 'onayli', 'reddedildi');
  ALTER TABLE "hizmetler" ADD COLUMN "dogrulama_durumu" "enum_hizmetler_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "hizmetler" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "hizmetler" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "hizmetler" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_hizmetler_v" ADD COLUMN "version_dogrulama_durumu" "enum__hizmetler_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_hizmetler_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_hizmetler_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_hizmetler_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "kullanim_alanlari" ADD COLUMN "dogrulama_durumu" "enum_kullanim_alanlari_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "kullanim_alanlari" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "kullanim_alanlari" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "kullanim_alanlari" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_kullanim_alanlari_v" ADD COLUMN "version_dogrulama_durumu" "enum__kullanim_alanlari_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_kullanim_alanlari_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_kullanim_alanlari_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_kullanim_alanlari_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "islem_secenekleri" ADD COLUMN "dogrulama_durumu" "enum_islem_secenekleri_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "islem_secenekleri" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "islem_secenekleri" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "islem_secenekleri" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_islem_secenekleri_v" ADD COLUMN "version_dogrulama_durumu" "enum__islem_secenekleri_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_islem_secenekleri_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_islem_secenekleri_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_islem_secenekleri_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "uygulamalar" ADD COLUMN "yayin_izni" boolean DEFAULT false;
  ALTER TABLE "uygulamalar" ADD COLUMN "izin_notu" varchar;
  ALTER TABLE "uygulamalar" ADD COLUMN "dogrulama_durumu" "enum_uygulamalar_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "uygulamalar" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "uygulamalar" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "uygulamalar" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_uygulamalar_v" ADD COLUMN "version_yayin_izni" boolean DEFAULT false;
  ALTER TABLE "_uygulamalar_v" ADD COLUMN "version_izin_notu" varchar;
  ALTER TABLE "_uygulamalar_v" ADD COLUMN "version_dogrulama_durumu" "enum__uygulamalar_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_uygulamalar_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_uygulamalar_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_uygulamalar_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "sss" ADD COLUMN "dogrulama_durumu" "enum_sss_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "sss" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "sss" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "sss" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_sss_v" ADD COLUMN "version_dogrulama_durumu" "enum__sss_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_sss_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_sss_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_sss_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "rehber_yazilari" ADD COLUMN "dogrulama_durumu" "enum_rehber_yazilari_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "rehber_yazilari" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "rehber_yazilari" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "rehber_yazilari" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_rehber_yazilari_v" ADD COLUMN "version_dogrulama_durumu" "enum__rehber_yazilari_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_rehber_yazilari_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_rehber_yazilari_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_rehber_yazilari_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "sayfalar" ADD COLUMN "dogrulama_durumu" "enum_sayfalar_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "sayfalar" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "sayfalar" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "sayfalar" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_sayfalar_v" ADD COLUMN "version_dogrulama_durumu" "enum__sayfalar_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_sayfalar_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_sayfalar_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_sayfalar_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "kampanyalar" ADD COLUMN "dogrulama_durumu" "enum_kampanyalar_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "kampanyalar" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "kampanyalar" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "kampanyalar" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_kampanyalar_v" ADD COLUMN "version_dogrulama_durumu" "enum__kampanyalar_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_kampanyalar_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_kampanyalar_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_kampanyalar_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "yorumlar" ADD COLUMN "yayin_izni" boolean DEFAULT false;
  ALTER TABLE "yorumlar" ADD COLUMN "dogrulama_durumu" "enum_yorumlar_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "yorumlar" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "yorumlar" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "yorumlar" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "_yorumlar_v" ADD COLUMN "version_yayin_izni" boolean DEFAULT false;
  ALTER TABLE "_yorumlar_v" ADD COLUMN "version_dogrulama_durumu" "enum__yorumlar_v_version_dogrulama_durumu" DEFAULT 'bekliyor';
  ALTER TABLE "_yorumlar_v" ADD COLUMN "version_onaylayan" varchar;
  ALTER TABLE "_yorumlar_v" ADD COLUMN "version_dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "_yorumlar_v" ADD COLUMN "version_dahili_kaynak_notu" varchar;
  ALTER TABLE "medyalar" ADD COLUMN "yayin_izni" boolean DEFAULT false NOT NULL;
  ALTER TABLE "medyalar" ADD COLUMN "dogrulama_durumu" "enum_medyalar_dogrulama_durumu" DEFAULT 'bekliyor' NOT NULL;
  ALTER TABLE "medyalar" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "medyalar" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "medyalar" ADD COLUMN "dahili_kaynak_notu" varchar;
  ALTER TABLE "dosyalar" ADD COLUMN "dogrulama_durumu" "enum_dosyalar_dogrulama_durumu" DEFAULT 'bekliyor' NOT NULL;
  ALTER TABLE "dosyalar" ADD COLUMN "onaylayan" varchar;
  ALTER TABLE "dosyalar" ADD COLUMN "dogrulama_tarihi" timestamp(3) with time zone;
  ALTER TABLE "dosyalar" ADD COLUMN "dahili_kaynak_notu" varchar;`)
}
