/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    yoneticiler: YoneticilerAuthOperations;
  };
  blocks: {};
  collections: {
    yoneticiler: Yoneticiler;
    hizmetler: Hizmetler;
    kullanim_alanlari: KullanimAlanlari;
    islem_secenekleri: IslemSecenekleri;
    uygulamalar: Uygulamalar;
    sss: Sss;
    rehber_yazilari: RehberYazilari;
    sayfalar: Sayfalar;
    kampanyalar: Kampanyalar;
    yorumlar: Yorumlar;
    hizmet_bolgeleri: HizmetBolgeleri;
    medyalar: Medyalar;
    dosyalar: Dosyalar;
    yonlendirmeler: Yonlendirmeler;
    denetim_kaydi: DenetimKaydi;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    yoneticiler: YoneticilerSelect<false> | YoneticilerSelect<true>;
    hizmetler: HizmetlerSelect<false> | HizmetlerSelect<true>;
    kullanim_alanlari: KullanimAlanlariSelect<false> | KullanimAlanlariSelect<true>;
    islem_secenekleri: IslemSecenekleriSelect<false> | IslemSecenekleriSelect<true>;
    uygulamalar: UygulamalarSelect<false> | UygulamalarSelect<true>;
    sss: SssSelect<false> | SssSelect<true>;
    rehber_yazilari: RehberYazilariSelect<false> | RehberYazilariSelect<true>;
    sayfalar: SayfalarSelect<false> | SayfalarSelect<true>;
    kampanyalar: KampanyalarSelect<false> | KampanyalarSelect<true>;
    yorumlar: YorumlarSelect<false> | YorumlarSelect<true>;
    hizmet_bolgeleri: HizmetBolgeleriSelect<false> | HizmetBolgeleriSelect<true>;
    medyalar: MedyalarSelect<false> | MedyalarSelect<true>;
    dosyalar: DosyalarSelect<false> | DosyalarSelect<true>;
    yonlendirmeler: YonlendirmelerSelect<false> | YonlendirmelerSelect<true>;
    denetim_kaydi: DenetimKaydiSelect<false> | DenetimKaydiSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site_ayarlari: SiteAyarlari;
    ana_sayfa_icerigi: AnaSayfaIcerigi;
    ust_bilgi: UstBilgi;
    alt_bilgi: AltBilgi;
    iletisim_bilgileri: IletisimBilgileri;
    entegrasyon_ayarlari: EntegrasyonAyarlari;
  };
  globalsSelect: {
    site_ayarlari: SiteAyarlariSelect<false> | SiteAyarlariSelect<true>;
    ana_sayfa_icerigi: AnaSayfaIcerigiSelect<false> | AnaSayfaIcerigiSelect<true>;
    ust_bilgi: UstBilgiSelect<false> | UstBilgiSelect<true>;
    alt_bilgi: AltBilgiSelect<false> | AltBilgiSelect<true>;
    iletisim_bilgileri: IletisimBilgileriSelect<false> | IletisimBilgileriSelect<true>;
    entegrasyon_ayarlari: EntegrasyonAyarlariSelect<false> | EntegrasyonAyarlariSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Yoneticiler;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface YoneticilerAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * Panel kullanıcılarını ve yetkilerini yönetir. Yeni hesapları yalnız mevcut yönetici oluşturabilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yoneticiler".
 */
export interface Yoneticiler {
  id: number;
  /**
   * Yönetici yayınlama, onay, izin ve kullanıcı işlemlerini yapabilir. Editör yalnız taslak içerik hazırlayabilir.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'yoneticiler';
}
/**
 * Sitede sunulan cam ve ayna hizmetlerini, detay sayfalarını ve ana sayfa hizmet satırlarını yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hizmetler".
 */
export interface Hizmetler {
  id: number;
  /**
   * Hizmet listesinde ve hizmet detay sayfasında büyük başlık olarak görünür.
   */
  ad: string;
  /**
   * İlk kayıtta başlıktan otomatik oluşturulur. Mevcut bağlantıların bozulmaması için sonradan değiştirilemez.
   */
  slug?: string | null;
  /**
   * Liste satırında, kartta veya giriş özetinde görünen kısa metindir; detay sayfasındaki uzun içeriğin yerini tutmaz.
   */
  ozet: string;
  /**
   * Detay sayfasının ana metin alanını oluşturur. Başlık, paragraf, liste ve güvenli bağlantılar burada düzenlenir.
   */
  aciklama?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Hizmet liste satırında ve hizmet detay sayfasının üst görsel alanında kullanılır.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  /**
   * Bu hizmetin ev, ofis, banyo gibi hangi kullanım içerikleriyle ilişkili olduğunu belirtir.
   */
  kullanim_alanlari?: (number | KullanimAlanlari)[] | null;
  /**
   * Bu hizmet için gerçekten sunulan cam/ayna türü, renk, kalınlık veya kenar işlemlerini bağlar.
   */
  islem_secenekleri?: (number | IslemSecenekleri)[] | null;
  /**
   * Bu hizmetle bağlantılı soru-cevap kayıtlarını seçer.
   */
  sss?: (number | Sss)[] | null;
  /**
   * Hizmet detayındaki WhatsApp düğmesine basıldığında hazırlanan başlangıç mesajını değiştirir. Boşsa genel WhatsApp mesajı kullanılır.
   */
  whatsapp_mesaji?: string | null;
  /**
   * Küçük sayı daha önce görünür. Ana sayfadaki özel seçim sırası ayrıca “Ana sayfa içeriği” alanından belirlenir.
   */
  sira: number;
  /**
   * Google sonuçları ve sosyal medya paylaşım önizlemesi için kullanılan alanlar.
   */
  seo?: {
    /**
     * Tarayıcı sekmesinde ve arama sonuçlarında görünen başlık. Boşsa içerik başlığı kullanılır.
     */
    baslik?: string | null;
    /**
     * Arama sonucunda başlığın altında gösterilebilen kısa açıklama. Sayfanın görünür ana metnini değiştirmez.
     */
    aciklama?: string | null;
    /**
     * Kapalıysa bu içerik için noindex üretilir. Taslaklar bu ayardan bağımsız olarak genel sitede görünmez.
     */
    indekslenebilir?: boolean | null;
    /**
     * Bağlantı WhatsApp veya sosyal medyada paylaşıldığında kullanılan önizleme görseli; sayfa içindeki kapak görselini değiştirmez.
     */
    paylasim_gorseli?: (number | null) | Medyalar;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Logo, kapak ve uygulama görsellerini yükler.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medyalar".
 */
export interface Medyalar {
  id: number;
  /**
   * Görseli göremeyen kullanıcıya ne olduğunu anlatır. Görseldeki gerçek içeriği kısa ve nesnel yazın; “resim” diye başlamayın.
   */
  alt: string;
  /**
   * Fotoğrafın kim tarafından çekildiği veya kullanım hakkının nereden geldiğine dair dahili kanıttır; sitede gösterilmez.
   */
  kaynak: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    kucuk?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    buyuk?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    dikey?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Hizmetleri kullanım bağlamına göre gruplamak için ev, ofis, banyo, mağaza gibi içerik sayfalarını yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kullanim_alanlari".
 */
export interface KullanimAlanlari {
  id: number;
  /**
   * Kullanım alanı liste ve detay sayfasında büyük başlık olarak kullanılır.
   */
  ad: string;
  /**
   * İlk kayıtta başlıktan otomatik oluşturulur. Mevcut bağlantıların bozulmaması için sonradan değiştirilemez.
   */
  slug?: string | null;
  /**
   * Liste satırında, kartta veya giriş özetinde görünen kısa metindir; detay sayfasındaki uzun içeriğin yerini tutmaz.
   */
  ozet: string;
  /**
   * Detay sayfasının ana metin alanını oluşturur. Başlık, paragraf, liste ve güvenli bağlantılar burada düzenlenir.
   */
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Kullanım alanı kartında veya detay sayfasının üst kısmında kullanılacak gerçek görseli seçer.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  /**
   * Bu kullanım alanında ziyaretçiye önerilecek hizmetleri bağlar.
   */
  hizmetler?: (number | Hizmetler)[] | null;
  /**
   * Küçük sayı daha önce görünür. Ana sayfadaki özel seçim sırası ayrıca “Ana sayfa içeriği” alanından belirlenir.
   */
  sira: number;
  /**
   * Google sonuçları ve sosyal medya paylaşım önizlemesi için kullanılan alanlar.
   */
  seo?: {
    /**
     * Tarayıcı sekmesinde ve arama sonuçlarında görünen başlık. Boşsa içerik başlığı kullanılır.
     */
    baslik?: string | null;
    /**
     * Arama sonucunda başlığın altında gösterilebilen kısa açıklama. Sayfanın görünür ana metnini değiştirmez.
     */
    aciklama?: string | null;
    /**
     * Kapalıysa bu içerik için noindex üretilir. Taslaklar bu ayardan bağımsız olarak genel sitede görünmez.
     */
    indekslenebilir?: boolean | null;
    /**
     * Bağlantı WhatsApp veya sosyal medyada paylaşıldığında kullanılan önizleme görseli; sayfa içindeki kapak görselini değiştirmez.
     */
    paylasim_gorseli?: (number | null) | Medyalar;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Cam/ayna türü, kalınlık, renk ve kenar işlemi gibi teknik seçenekleri yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islem_secenekleri".
 */
export interface IslemSecenekleri {
  id: number;
  /**
   * Ziyaretçiye gösterilebilecek teknik seçeneğin anlaşılır adı. Örnek: Füme cam veya rodajlı kenar.
   */
  ad: string;
  /**
   * Seçeneğin panelde ve ileride filtrelerde hangi teknik başlık altında gruplanacağını belirler.
   */
  tur: 'cam' | 'ayna' | 'kalinlik' | 'renk' | 'kenar' | 'diger';
  /**
   * Bu seçeneğin işletme tarafından doğrudan, dış kaynakla veya hiç sunulmadığını belirtir. Yanlış hizmet vaadini önler.
   */
  sunum_durumu: 'sunuluyor' | 'disaridan' | 'sunulmuyor';
  /**
   * Seçeneğin geçerli olduğu ölçü, ürün veya tedarik koşulunu açıklar; teyit edilmemiş kesin vaat yazmayın.
   */
  aciklama?: string | null;
  /**
   * Küçük sayı daha önce görünür. Ana sayfadaki özel seçim sırası ayrıca “Ana sayfa içeriği” alanından belirlenir.
   */
  sira: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ziyaretçilerin sık sorduğu sorulara kısa ve doğrudan yanıtlar sağlar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sss".
 */
export interface Sss {
  id: number;
  /**
   * SSS başlığı olarak ziyaretçiye gösterilecek açık ve doğal dilde soru.
   */
  soru: string;
  /**
   * Sorunun altında gösterilecek yanıt. Kesinleşmemiş fiyat, süre, garanti veya montaj vaadi yazmayın.
   */
  yanit: string;
  /**
   * Bu sorunun hangi hizmet sayfalarında ilgili olduğunu belirtir.
   */
  hizmetler?: (number | Hizmetler)[] | null;
  /**
   * Küçük sayı daha önce görünür. Ana sayfadaki özel seçim sırası ayrıca “Ana sayfa içeriği” alanından belirlenir.
   */
  sira: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Görselli uygulama anlatımlarını yönetir. Ana sayfanın koyu bölümü bu kayıtlardan beslenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uygulamalar".
 */
export interface Uygulamalar {
  id: number;
  /**
   * Ana sayfadaki koyu iş örneğinde ve uygulama detayında büyük başlık olarak görünür.
   */
  ad: string;
  /**
   * İlk kayıtta başlıktan otomatik oluşturulur. Mevcut bağlantıların bozulmaması için sonradan değiştirilemez.
   */
  slug?: string | null;
  /**
   * Liste satırında, kartta veya giriş özetinde görünen kısa metindir; detay sayfasındaki uzun içeriğin yerini tutmaz.
   */
  ozet: string;
  /**
   * İş örneğinin küçük üst etiketinde mekân veya kullanım türünü belirtir. Örnek: Banyo / özel ölçü.
   */
  kullanim?: string | null;
  /**
   * Projede gerçekten kullanılan, işletme tarafından teyit edilmiş malzeme bilgisidir.
   */
  malzeme?: string | null;
  /**
   * Projede gerçekten uygulanan kesim, kenar, temper veya montaj işlemini kaydeder.
   */
  islem?: string | null;
  /**
   * Detay sayfasının ana metin alanını oluşturur. Başlık, paragraf, liste ve güvenli bağlantılar burada düzenlenir.
   */
  aciklama?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ana sayfanın koyu seçili işler bölümünde ve uygulama sayfasında gösterilecek gerçek proje fotoğraflarıdır. İlk görsel ana görsel olur.
   */
  gorseller: (number | Medyalar)[];
  /**
   * Uygulamanın kategorilerini seçer. Seçilen hizmetler, Uygulamalar sayfasındaki müşteri filtrelerini oluşturur ve işi ilgili hizmet detaylarıyla ilişkilendirir.
   */
  hizmetler?: (number | Hizmetler)[] | null;
  /**
   * Küçük sayı daha önce görünür. Ana sayfadaki özel seçim sırası ayrıca “Ana sayfa içeriği” alanından belirlenir.
   */
  sira: number;
  /**
   * Google sonuçları ve sosyal medya paylaşım önizlemesi için kullanılan alanlar.
   */
  seo?: {
    /**
     * Tarayıcı sekmesinde ve arama sonuçlarında görünen başlık. Boşsa içerik başlığı kullanılır.
     */
    baslik?: string | null;
    /**
     * Arama sonucunda başlığın altında gösterilebilen kısa açıklama. Sayfanın görünür ana metnini değiştirmez.
     */
    aciklama?: string | null;
    /**
     * Kapalıysa bu içerik için noindex üretilir. Taslaklar bu ayardan bağımsız olarak genel sitede görünmez.
     */
    indekslenebilir?: boolean | null;
    /**
     * Bağlantı WhatsApp veya sosyal medyada paylaşıldığında kullanılan önizleme görseli; sayfa içindeki kapak görselini değiştirmez.
     */
    paylasim_gorseli?: (number | null) | Medyalar;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Cam ve ayna seçimi hakkında bilgilendirici yazıları yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rehber_yazilari".
 */
export interface RehberYazilari {
  id: number;
  /**
   * Rehber liste ve detay sayfasındaki büyük başlığı değiştirir.
   */
  baslik: string;
  /**
   * İlk kayıtta başlıktan otomatik oluşturulur. Mevcut bağlantıların bozulmaması için sonradan değiştirilemez.
   */
  slug?: string | null;
  /**
   * Liste satırında, kartta veya giriş özetinde görünen kısa metindir; detay sayfasındaki uzun içeriğin yerini tutmaz.
   */
  ozet: string;
  /**
   * Detay sayfasının ana metin alanını oluşturur. Başlık, paragraf, liste ve güvenli bağlantılar burada düzenlenir.
   */
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Rehber kartı ve yazı üst bölümünde kullanılan görseli değiştirir.
   */
  kapak_gorseli?: (number | null) | Medyalar;
  /**
   * Yazıdaki teknik bilgileri kontrol eden yetkili veya uzman kaydı. Doğrulanmamış bir isim eklemeyin.
   */
  kontrol_eden?: string | null;
  /**
   * Google sonuçları ve sosyal medya paylaşım önizlemesi için kullanılan alanlar.
   */
  seo?: {
    /**
     * Tarayıcı sekmesinde ve arama sonuçlarında görünen başlık. Boşsa içerik başlığı kullanılır.
     */
    baslik?: string | null;
    /**
     * Arama sonucunda başlığın altında gösterilebilen kısa açıklama. Sayfanın görünür ana metnini değiştirmez.
     */
    aciklama?: string | null;
    /**
     * Kapalıysa bu içerik için noindex üretilir. Taslaklar bu ayardan bağımsız olarak genel sitede görünmez.
     */
    indekslenebilir?: boolean | null;
    /**
     * Bağlantı WhatsApp veya sosyal medyada paylaşıldığında kullanılan önizleme görseli; sayfa içindeki kapak görselini değiştirmez.
     */
    paylasim_gorseli?: (number | null) | Medyalar;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Hakkımızda veya bilgilendirme gibi bağımsız içerik sayfalarını yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sayfalar".
 */
export interface Sayfalar {
  id: number;
  /**
   * Bağımsız sayfanın ana başlığı ve varsayılan tarayıcı başlığıdır.
   */
  baslik: string;
  /**
   * İlk kayıtta başlıktan otomatik oluşturulur. Mevcut bağlantıların bozulmaması için sonradan değiştirilemez.
   */
  slug?: string | null;
  /**
   * Liste satırında, kartta veya giriş özetinde görünen kısa metindir; detay sayfasındaki uzun içeriğin yerini tutmaz.
   */
  ozet: string;
  /**
   * Detay sayfasının ana metin alanını oluşturur. Başlık, paragraf, liste ve güvenli bağlantılar burada düzenlenir.
   */
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Google sonuçları ve sosyal medya paylaşım önizlemesi için kullanılan alanlar.
   */
  seo?: {
    /**
     * Tarayıcı sekmesinde ve arama sonuçlarında görünen başlık. Boşsa içerik başlığı kullanılır.
     */
    baslik?: string | null;
    /**
     * Arama sonucunda başlığın altında gösterilebilen kısa açıklama. Sayfanın görünür ana metnini değiştirmez.
     */
    aciklama?: string | null;
    /**
     * Kapalıysa bu içerik için noindex üretilir. Taslaklar bu ayardan bağımsız olarak genel sitede görünmez.
     */
    indekslenebilir?: boolean | null;
    /**
     * Bağlantı WhatsApp veya sosyal medyada paylaşıldığında kullanılan önizleme görseli; sayfa içindeki kapak görselini değiştirmez.
     */
    paylasim_gorseli?: (number | null) | Medyalar;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Yayınlanmış ve tarih aralığı geçerli kampanyalar site açıldığında pencere olarak gösterilir. Geçerli birden fazla kampanya varsa ziyaretçiye rastgele biri gösterilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kampanyalar".
 */
export interface Kampanyalar {
  id: number;
  /**
   * Açılış penceresinde ziyaretçinin göreceği ana başlık.
   */
  baslik: string;
  /**
   * Liste satırında, kartta veya giriş özetinde görünen kısa metindir; detay sayfasındaki uzun içeriğin yerini tutmaz.
   */
  ozet: string;
  /**
   * Detay sayfasının ana metin alanını oluşturur. Başlık, paragraf, liste ve güvenli bağlantılar burada düzenlenir.
   */
  kosullar?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Kampanyanın geçerli olmaya başladığı tarih. Görünür metindeki tarihle aynı olmalıdır.
   */
  baslangic: string;
  /**
   * Kampanyanın sona erdiği tarih ve saat. Bu andan sonra pencere otomatik olarak gösterilmez.
   */
  bitis: string;
  /**
   * Kampanya açılış penceresinin üst kısmında kullanılacak görseli değiştirir.
   */
  gorsel?: (number | null) | Medyalar;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Google veya web sitesi üzerinden alınan gerçek müşteri yorumlarından hangilerinin sitede gösterileceğini yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yorumlar".
 */
export interface Yorumlar {
  id: number;
  /**
   * Yorum yanında ziyaretçiye gösterilecek, sahibinin onayladığı ad veya kurum adı.
   */
  gostergelik_ad: string;
  /**
   * İzin verilen gerçek yorum metni. Anlamını değiştirecek düzenleme veya temsili metin eklemeyin.
   */
  yorum: string;
  /**
   * Ziyaretçiye gösterilecek kaynak adı. Örnek: Google veya Web sitesi.
   */
  kaynak: string;
  /**
   * Google yorumunun veya doğrulanabilir kaynak sayfasının https:// ile başlayan bağlantısı. Web sitesi içi yorumlarda boş kalabilir.
   */
  kaynak_baglantisi?: string | null;
  /**
   * Kaynakta yıldız puanı varsa 1–5 arasında girin; yoksa boş bırakın.
   */
  puan?: number | null;
  /**
   * Açık ve Yayınlandı durumundaysa yorum /yorumlar ve Bilgi Merkezi sayfalarında görünür.
   */
  sitede_goster?: boolean | null;
  /**
   * Küçük sayı daha önce görünür. Ana sayfadaki özel seçim sırası ayrıca “Ana sayfa içeriği” alanından belirlenir.
   */
  sira: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ankara bölge sayfasındaki 25 ilçeyi ve varsa ilçeye özel çalışma koşullarını yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hizmet_bolgeleri".
 */
export interface HizmetBolgeleri {
  id: number;
  /**
   * Ana sayfa ve /hizmet-bolgeleri listesindeki görünen ilçe adını değiştirir.
   */
  ad: string;
  /**
   * Küçük sayı daha önce görünür. Ana sayfadaki özel seçim sırası ayrıca “Ana sayfa içeriği” alanından belirlenir.
   */
  sira: number;
  /**
   * Açıksa ilçe ana sayfa ve bölge listesindeki hedef kapsamda görünür. Bu seçim kesin montaj veya nakliye vaadi değildir.
   */
  hedef_kapsam: boolean;
  /**
   * İlçeye özel ve işletme tarafından doğrulanmış koşul varsa bölge listesinde ilçe adının altında görünür. Boşsa hizmet/montaj vaadi gösterilmez.
   */
  operasyon_teyidi?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ziyaretçiye sunulabilecek PDF belgelerini yönetir; proje fotoğrafları için Medyalar bölümünü kullanın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dosyalar".
 */
export interface Dosyalar {
  id: number;
  /**
   * PDF bağlantısı yanında ziyaretçiye gösterilecek anlaşılır belge adı.
   */
  baslik: string;
  /**
   * Belgenin ne içerdiğini ve hangi durumda kullanılacağını açıklar.
   */
  aciklama?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Eski veya değişen site adreslerini yeni ilgili sayfaya yönlendirmek için kullanılır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yonlendirmeler".
 */
export interface Yonlendirmeler {
  id: number;
  /**
   * Ziyaretçinin veya arama motorunun gelebileceği eski yol. Örnek: /eski-hizmet.
   */
  kaynak: string;
  /**
   * Eski yolun yönleneceği çalışan yeni sayfa. Örnek: /hizmetler/ozel-olcu-ayna.
   */
  hedef: string;
  /**
   * Adres değişikliği kalıcıysa açık bırakın. Geçici yönlendirme yalnız gerçekten geçici durumlarda kullanılmalıdır.
   */
  kalici?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kritik panel işlemlerinin sistem tarafından oluşturulan salt okunur izlerini gösterir; elle kayıt eklenmez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "denetim_kaydi".
 */
export interface DenetimKaydi {
  id: number;
  /**
   * Sistem tarafından kaydedilen işlem türü.
   */
  islem: string;
  /**
   * İşlemin hangi içerik veya ayar alanında gerçekleştiğini belirtir.
   */
  koleksiyon: string;
  /**
   * İşlem belirli bir kayda aitse o kaydın dahili kimliği.
   */
  kayit_id?: string | null;
  /**
   * İşlemi yapan panel kullanıcısını gösterir.
   */
  yonetici?: (number | null) | Yoneticiler;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'yoneticiler';
        value: number | Yoneticiler;
      } | null)
    | ({
        relationTo: 'hizmetler';
        value: number | Hizmetler;
      } | null)
    | ({
        relationTo: 'kullanim_alanlari';
        value: number | KullanimAlanlari;
      } | null)
    | ({
        relationTo: 'islem_secenekleri';
        value: number | IslemSecenekleri;
      } | null)
    | ({
        relationTo: 'uygulamalar';
        value: number | Uygulamalar;
      } | null)
    | ({
        relationTo: 'sss';
        value: number | Sss;
      } | null)
    | ({
        relationTo: 'rehber_yazilari';
        value: number | RehberYazilari;
      } | null)
    | ({
        relationTo: 'sayfalar';
        value: number | Sayfalar;
      } | null)
    | ({
        relationTo: 'kampanyalar';
        value: number | Kampanyalar;
      } | null)
    | ({
        relationTo: 'yorumlar';
        value: number | Yorumlar;
      } | null)
    | ({
        relationTo: 'hizmet_bolgeleri';
        value: number | HizmetBolgeleri;
      } | null)
    | ({
        relationTo: 'medyalar';
        value: number | Medyalar;
      } | null)
    | ({
        relationTo: 'dosyalar';
        value: number | Dosyalar;
      } | null)
    | ({
        relationTo: 'yonlendirmeler';
        value: number | Yonlendirmeler;
      } | null)
    | ({
        relationTo: 'denetim_kaydi';
        value: number | DenetimKaydi;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'yoneticiler';
    value: number | Yoneticiler;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'yoneticiler';
    value: number | Yoneticiler;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yoneticiler_select".
 */
export interface YoneticilerSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hizmetler_select".
 */
export interface HizmetlerSelect<T extends boolean = true> {
  ad?: T;
  slug?: T;
  ozet?: T;
  aciklama?: T;
  kapak_gorseli?: T;
  kullanim_alanlari?: T;
  islem_secenekleri?: T;
  sss?: T;
  whatsapp_mesaji?: T;
  sira?: T;
  seo?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        indekslenebilir?: T;
        paylasim_gorseli?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kullanim_alanlari_select".
 */
export interface KullanimAlanlariSelect<T extends boolean = true> {
  ad?: T;
  slug?: T;
  ozet?: T;
  icerik?: T;
  kapak_gorseli?: T;
  hizmetler?: T;
  sira?: T;
  seo?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        indekslenebilir?: T;
        paylasim_gorseli?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "islem_secenekleri_select".
 */
export interface IslemSecenekleriSelect<T extends boolean = true> {
  ad?: T;
  tur?: T;
  sunum_durumu?: T;
  aciklama?: T;
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uygulamalar_select".
 */
export interface UygulamalarSelect<T extends boolean = true> {
  ad?: T;
  slug?: T;
  ozet?: T;
  kullanim?: T;
  malzeme?: T;
  islem?: T;
  aciklama?: T;
  gorseller?: T;
  hizmetler?: T;
  sira?: T;
  seo?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        indekslenebilir?: T;
        paylasim_gorseli?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sss_select".
 */
export interface SssSelect<T extends boolean = true> {
  soru?: T;
  yanit?: T;
  hizmetler?: T;
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rehber_yazilari_select".
 */
export interface RehberYazilariSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  ozet?: T;
  icerik?: T;
  kapak_gorseli?: T;
  kontrol_eden?: T;
  seo?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        indekslenebilir?: T;
        paylasim_gorseli?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sayfalar_select".
 */
export interface SayfalarSelect<T extends boolean = true> {
  baslik?: T;
  slug?: T;
  ozet?: T;
  icerik?: T;
  seo?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        indekslenebilir?: T;
        paylasim_gorseli?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kampanyalar_select".
 */
export interface KampanyalarSelect<T extends boolean = true> {
  baslik?: T;
  ozet?: T;
  kosullar?: T;
  baslangic?: T;
  bitis?: T;
  gorsel?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yorumlar_select".
 */
export interface YorumlarSelect<T extends boolean = true> {
  gostergelik_ad?: T;
  yorum?: T;
  kaynak?: T;
  kaynak_baglantisi?: T;
  puan?: T;
  sitede_goster?: T;
  sira?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hizmet_bolgeleri_select".
 */
export interface HizmetBolgeleriSelect<T extends boolean = true> {
  ad?: T;
  sira?: T;
  hedef_kapsam?: T;
  operasyon_teyidi?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medyalar_select".
 */
export interface MedyalarSelect<T extends boolean = true> {
  alt?: T;
  kaynak?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        kucuk?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        buyuk?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        dikey?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dosyalar_select".
 */
export interface DosyalarSelect<T extends boolean = true> {
  baslik?: T;
  aciklama?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yonlendirmeler_select".
 */
export interface YonlendirmelerSelect<T extends boolean = true> {
  kaynak?: T;
  hedef?: T;
  kalici?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "denetim_kaydi_select".
 */
export interface DenetimKaydiSelect<T extends boolean = true> {
  islem?: T;
  koleksiyon?: T;
  kayit_id?: T;
  yonetici?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Marka kimliği ve varsayılan SEO bilgileri.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_ayarlari".
 */
export interface SiteAyarlari {
  id: number;
  /**
   * Sayfa başlığı, erişilebilir logo etiketi ve varsayılan SEO kimliğinde kullanılır.
   */
  firma_adi: string;
  /**
   * Logo görseli seçilmemişse üst ve alt bilgide büyük marka yazısı olarak görünür. Örnek: RINA.
   */
  marka_kisa: string;
  /**
   * Üst ve alt bilgide marka adının veya yüklenen logonun yanında küçük satırlar halinde görünür.
   */
  marka_alt?: string | null;
  /**
   * Özel SEO açıklaması boş olduğunda ana sayfanın varsayılan meta açıklaması olur; sayfa gövdesinde otomatik görünmez.
   */
  kisa_aciklama: string;
  /**
   * Seçildiğinde sitenin sol üst ve alt bölümündeki yazının yerini alır. PageSpeed için şeffaf WebP/SVG ve en fazla 100 KB kullanın; daha büyük dosyada hızlı yazı logosu gösterilir.
   */
  logo?: (number | null) | Medyalar;
  /**
   * Tarayıcı sekmesi ve yer imlerinde görünür. En fazla 100 KB kullanın; daha büyük dosyada hızlı varsayılan Rina simgesi gösterilir.
   */
  favicon?: (number | null) | Medyalar;
  /**
   * Sitenin genel zemin, yazı, vurgu, çizgi ve form renklerini altı haneli HEX kodlarıyla yönetin. Örnek: #ff6254.
   */
  renkler: {
    /**
     * Sayfaların açık renkli ana arka planı.
     */
    zemin: string;
    /**
     * Başlıklar, metinler, çerçeveler ve koyu bölümlerin zemini.
     */
    metin: string;
    /**
     * Mercan renkli başlıklar, çizgiler ve ana düğmeler.
     */
    vurgu: string;
    /**
     * Kartları ve liste satırlarını ayıran hafif çizgiler.
     */
    cizgi: string;
    /**
     * Ana sayfadaki teklif formunun açık renkli arka planı.
     */
    form_zemini: string;
    /**
     * Koyu zeminlerde kullanılan başlık ve metin rengi.
     */
    acik_metin: string;
  };
  /**
   * Google sonuçları ve sosyal medya paylaşım önizlemesi için kullanılan alanlar.
   */
  seo?: {
    /**
     * Tarayıcı sekmesinde ve arama sonuçlarında görünen başlık. Boşsa içerik başlığı kullanılır.
     */
    baslik?: string | null;
    /**
     * Arama sonucunda başlığın altında gösterilebilen kısa açıklama. Sayfanın görünür ana metnini değiştirmez.
     */
    aciklama?: string | null;
    /**
     * Kapalıysa bu içerik için noindex üretilir. Taslaklar bu ayardan bağımsız olarak genel sitede görünmez.
     */
    indekslenebilir?: boolean | null;
    /**
     * Bağlantı WhatsApp veya sosyal medyada paylaşıldığında kullanılan önizleme görseli; sayfa içindeki kapak görselini değiştirmez.
     */
    paylasim_gorseli?: (number | null) | Medyalar;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Rina ana sayfasının bütün metinlerini, görsellerini ve seçili kayıtlarını buradan yönetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ana_sayfa_icerigi".
 */
export interface AnaSayfaIcerigi {
  id: number;
  /**
   * Ana sayfanın ilk ekranında, büyük başlığın üstündeki küçük ve harf aralıklı satırı değiştirir.
   */
  hero_etiket?: string | null;
  /**
   * İlk ekrandaki büyük siyah başlığın birinci satırı.
   */
  hero_baslik_1?: string | null;
  /**
   * İlk ekrandaki içi boş, konturlu büyük başlık satırını değiştirir.
   */
  hero_vurgu?: string | null;
  /**
   * İlk ekrandaki büyük siyah başlığın son satırı.
   */
  hero_baslik_2?: string | null;
  /**
   * Büyük başlığın altında, WhatsApp düğmesinin üstünde görünen kısa açıklamayı değiştirir.
   */
  hero_aciklama?: string | null;
  /**
   * Ana sayfanın ilk ekranında sağdaki büyük görsel alanını değiştirir. Boş bırakılırsa dekoratif ayna çizimi görünür.
   */
  hero_gorseli?: (number | null) | Medyalar;
  /**
   * Sağdaki giriş görselinin alt şeridinde, sağ tarafta görünen kısa bilgiyi değiştirir.
   */
  hero_gorsel_etiketi?: string | null;
  /**
   * İlk ekrandaki mercan renkli ana WhatsApp düğmesinde görünen yazıyı değiştirir.
   */
  hero_cta_etiketi?: string | null;
  /**
   * Kapalıysa ana sayfadaki büyük “Standart bir ihtiyaç yok” anlatım bölümü tamamen gizlenir.
   */
  yaklasim_gorunsun?: boolean | null;
  /**
   * Bölümün sol üstünde küçük numara olarak görünür. Örnek: 01.
   */
  yaklasim_sira?: string | null;
  /**
   * Yaklaşım bölümündeki büyük siyah metni değiştirir.
   */
  yaklasim_baslik?: string | null;
  /**
   * Büyük siyah metnin hemen altındaki mercan renkli büyük metni değiştirir.
   */
  yaklasim_vurgu?: string | null;
  /**
   * Yaklaşım bölümünün sağ sütunundaki destekleyici paragrafı değiştirir.
   */
  yaklasim_aciklama?: string | null;
  /**
   * Kapalıysa ana sayfadaki hizmet liste satırları gizlenir. Seçili yayınlanmış hizmet yoksa bölüm zaten gösterilmez.
   */
  hizmetler_gorunsun?: boolean | null;
  /**
   * Hizmetler bölüm başlığının üstündeki küçük satırı değiştirir.
   */
  hizmetler_etiket?: string | null;
  /**
   * Hizmet liste satırlarının üstündeki büyük “Ne yapıyoruz?” başlığını değiştirir.
   */
  hizmetler_baslik?: string | null;
  /**
   * Hizmetler bölüm başlığının sağındaki kısa açıklamayı değiştirir.
   */
  hizmetler_aciklama?: string | null;
  /**
   * Ana sayfadaki hizmet satırlarını ve sıralarını belirler. Yalnız yayınlanmış hizmetler görünür.
   */
  secili_hizmetler?: (number | Hizmetler)[] | null;
  /**
   * Kapalıysa ana sayfadaki koyu zeminli gerçek işler bölümü gizlenir. Seçili izinli iş yoksa bölüm zaten gösterilmez.
   */
  uygulamalar_gorunsun?: boolean | null;
  /**
   * Koyu bölümde büyük başlığın üstündeki küçük satırı değiştirir.
   */
  uygulamalar_etiket?: string | null;
  /**
   * Ana sayfadaki koyu iş örnekleri bölümünün büyük başlığını değiştirir.
   */
  uygulamalar_baslik?: string | null;
  /**
   * Koyu bölüm başlığının sağındaki açıklama metnini değiştirir.
   */
  uygulamalar_aciklama?: string | null;
  /**
   * Koyu bölümde kullanılacak görsel kayıtları ve sıralarını belirler. Yalnız yayınlanmış kayıtlar görünür.
   */
  secili_uygulamalar?: (number | Uygulamalar)[] | null;
  /**
   * Kapalıysa ana sayfadaki numaralı çalışma adımları bölümü tamamen gizlenir.
   */
  surec_gorunsun?: boolean | null;
  /**
   * Süreç bölümünün sol üstündeki küçük satırı değiştirir.
   */
  surec_etiket?: string | null;
  /**
   * Süreç bölümünün sol sütunundaki büyük başlığı değiştirir.
   */
  surec_baslik?: string | null;
  /**
   * Süreç bölümünün sol altındaki altı mercan çizgili WhatsApp bağlantısının yazısını değiştirir.
   */
  surec_cta_etiketi?: string | null;
  /**
   * Süreç bölümünün sağındaki 01, 02, 03 şeklindeki satırları oluşturur; sürükleyerek sıralayabilirsiniz.
   */
  surec_adimlari?:
    | {
        /**
         * Numaranın yanında kalın görünen adım adı.
         */
        baslik: string;
        /**
         * Adım başlığının altında görünen kısa açıklama.
         */
        aciklama: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kapalıysa ana sayfadaki ilçe listesi ve bölge anlatımı gizlenir; ayrı bölge sayfasını silmez.
   */
  bolge_gorunsun?: boolean | null;
  /**
   * Ana sayfadaki bölge başlığının üstündeki küçük satırı değiştirir.
   */
  bolge_etiket?: string | null;
  /**
   * Ana sayfadaki ilçe listesinin solunda görünen büyük başlığı değiştirir.
   */
  bolge_baslik?: string | null;
  /**
   * Bölge başlığının altında görünen açıklamayı değiştirir. Kesin hizmet veya montaj vaadi yazmayın.
   */
  bolge_aciklama?: string | null;
  /**
   * Ana sayfanın mercan teklif panelinde başlığın üstündeki küçük satırı değiştirir.
   */
  teklif_etiket?: string | null;
  /**
   * Ana sayfanın altındaki mercan panelde görünen büyük başlığı değiştirir.
   */
  teklif_baslik?: string | null;
  /**
   * Mercan teklif panelinde başlığın altında görünen yönlendirme metnini değiştirir.
   */
  teklif_aciklama?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tüm sayfaların en üstündeki logo, menü bağlantıları ve WhatsApp alanını yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ust_bilgi".
 */
export interface UstBilgi {
  id: number;
  /**
   * Satır sırası sitedeki bağlantı sırasını belirler. Yalnız site içi sayfa veya bölüm bağlantısı kullanılır.
   */
  menu_ogeleri?:
    | {
        /**
         * Ziyaretçinin menüde veya alt bilgide okuyacağı metin.
         */
        etiket: string;
        /**
         * Örnek: /hizmetler, /hizmet-bolgeleri veya ana sayfa bölümü için #teklif.
         */
        baglanti: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kapalıysa masaüstü üst bilginin sağındaki WhatsApp numarası gizlenir; sayfadaki diğer WhatsApp düğmeleri etkilenmez.
   */
  cta_gorunsun?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tüm sayfaların en altındaki kısa metni, bağlantıları ve WhatsApp düğmesini yönetir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alt_bilgi".
 */
export interface AltBilgi {
  id: number;
  /**
   * Sayfanın en altında, logo ile bağlantıların arasında görünen kısa firma metnini değiştirir.
   */
  metin?: string | null;
  /**
   * Satır sırası sitedeki bağlantı sırasını belirler. Yalnız site içi sayfa veya bölüm bağlantısı kullanılır.
   */
  linkler?:
    | {
        /**
         * Ziyaretçinin menüde veya alt bilgide okuyacağı metin.
         */
        etiket: string;
        /**
         * Örnek: /hizmetler, /hizmet-bolgeleri veya ana sayfa bölümü için #teklif.
         */
        baglanti: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Müşteri iletişimi yalnız WhatsApp üzerinden yürür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iletisim_bilgileri".
 */
export interface IletisimBilgileri {
  id: number;
  /**
   * Üst bilgi, giriş, süreç, teklif, alt bilgi ve mobil sabit düğme dahil tüm WhatsApp bağlantılarının hedefini değiştirir. 90 ile başlayan yalnız rakamlı biçim önerilir.
   */
  whatsapp_numarasi: string;
  /**
   * Alt bilgi, mobil sabit düğme ve genel iletişim bağlantılarında görünen yazıyı değiştirir.
   */
  cta_etiketi: string;
  /**
   * Formdan mesaj hazırlandıktan sonra WhatsApp’ı açan son düğmenin yazısını değiştirir.
   */
  teklif_etiketi: string;
  /**
   * Form dışındaki WhatsApp düğmelerine basıldığında sohbet kutusuna hazırlanan başlangıç mesajıdır. Mesaj otomatik gönderilmez.
   */
  genel_mesaj: string;
  /**
   * Teklif formunun oluşturduğu mesajın ilk paragrafını değiştirir; kullanıcının girdiği bilgiler bunun altına eklenir.
   */
  teklif_girisi: string;
  /**
   * Doluysa alt bilgide görünür. Adres kesinleşmediyse boş bırakın.
   */
  adres?: string | null;
  /**
   * Doluysa alt bilgide görünür. Saatler kesinleşmediyse boş bırakın.
   */
  calisma_saatleri?: string | null;
  /**
   * Yalnız panel kullanıcılarının görebildiği çalışma notudur; siteye ve public API’ye çıkmaz. Kişisel veri veya parola yazmayın.
   */
  dahili_not?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sır saklamayın; yalnız doğrulama ve ölçüm kimlikleri.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entegrasyon_ayarlari".
 */
export interface EntegrasyonAyarlari {
  id: number;
  /**
   * Google Search Console mülk doğrulamasında kullanılan içerik kodudur. Tam HTML etiketi veya hesap parolası girmeyin.
   */
  search_console_dogrulama?: string | null;
  /**
   * Analitik entegrasyonunu açmak için kullanılır. İzin ve üretim kurulumu tamamlanmadan kapalı bırakın.
   */
  analytics_aktif?: boolean | null;
  /**
   * Onaylı analitik sağlayıcısının ölçüm kimliği. Mesaj, telefon, müşteri bilgisi veya gizli anahtar yazmayın.
   */
  analytics_kimligi?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_ayarlari_select".
 */
export interface SiteAyarlariSelect<T extends boolean = true> {
  firma_adi?: T;
  marka_kisa?: T;
  marka_alt?: T;
  kisa_aciklama?: T;
  logo?: T;
  favicon?: T;
  renkler?:
    | T
    | {
        zemin?: T;
        metin?: T;
        vurgu?: T;
        cizgi?: T;
        form_zemini?: T;
        acik_metin?: T;
      };
  seo?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        indekslenebilir?: T;
        paylasim_gorseli?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ana_sayfa_icerigi_select".
 */
export interface AnaSayfaIcerigiSelect<T extends boolean = true> {
  hero_etiket?: T;
  hero_baslik_1?: T;
  hero_vurgu?: T;
  hero_baslik_2?: T;
  hero_aciklama?: T;
  hero_gorseli?: T;
  hero_gorsel_etiketi?: T;
  hero_cta_etiketi?: T;
  yaklasim_gorunsun?: T;
  yaklasim_sira?: T;
  yaklasim_baslik?: T;
  yaklasim_vurgu?: T;
  yaklasim_aciklama?: T;
  hizmetler_gorunsun?: T;
  hizmetler_etiket?: T;
  hizmetler_baslik?: T;
  hizmetler_aciklama?: T;
  secili_hizmetler?: T;
  uygulamalar_gorunsun?: T;
  uygulamalar_etiket?: T;
  uygulamalar_baslik?: T;
  uygulamalar_aciklama?: T;
  secili_uygulamalar?: T;
  surec_gorunsun?: T;
  surec_etiket?: T;
  surec_baslik?: T;
  surec_cta_etiketi?: T;
  surec_adimlari?:
    | T
    | {
        baslik?: T;
        aciklama?: T;
        id?: T;
      };
  bolge_gorunsun?: T;
  bolge_etiket?: T;
  bolge_baslik?: T;
  bolge_aciklama?: T;
  teklif_etiket?: T;
  teklif_baslik?: T;
  teklif_aciklama?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ust_bilgi_select".
 */
export interface UstBilgiSelect<T extends boolean = true> {
  menu_ogeleri?:
    | T
    | {
        etiket?: T;
        baglanti?: T;
        id?: T;
      };
  cta_gorunsun?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alt_bilgi_select".
 */
export interface AltBilgiSelect<T extends boolean = true> {
  metin?: T;
  linkler?:
    | T
    | {
        etiket?: T;
        baglanti?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iletisim_bilgileri_select".
 */
export interface IletisimBilgileriSelect<T extends boolean = true> {
  whatsapp_numarasi?: T;
  cta_etiketi?: T;
  teklif_etiketi?: T;
  genel_mesaj?: T;
  teklif_girisi?: T;
  adres?: T;
  calisma_saatleri?: T;
  dahili_not?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entegrasyon_ayarlari_select".
 */
export interface EntegrasyonAyarlariSelect<T extends boolean = true> {
  search_console_dogrulama?: T;
  analytics_aktif?: T;
  analytics_kimligi?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}